name: movie_search_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  generated:
    path: ./generated/
  get: ^4.7.2
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  built_collection: ^5.1.1
  openapi_generator_annotations: ^6.1.0
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  file_picker: ^10.3.3
  device_info_plus: ^11.5.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  openapi_generator: ^6.1.0
  openapi_generator_cli: ^6.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/movie_search_assistant_icon.png"
  min_sdk_android: 21

